import { UnitType, DiscountType } from "./others";

export type Product = {
  id: string | number;
  name: string;
  purchase_price: string | number;
  unit_price: string | number;
  featured: number;
  status: number;
  featured_status: number;
  details: string;
  discount: number;
  images?: string[];
  added_by: string;
  attachment?: string;
  attributes?: string[];
  brand_id: number;
  category_ids: Record<string, any>[];
  choice_options: Array;
  colors: string[];
  created_at: string;
  current_stock?: number;
  denied_note: null;
  discount_type: DiscountType;
  flash_deal: any;
  free_shipping: number;
  meta_description: string;
  meta_image: string;
  meta_title: string;
  min_qty: number;
  published: number;
  refundable: number;
  request_status: number;
  slug: string;
  tax: number;
  tax_type: string;
  thumbnail: string;
  translations: [];
  unit: UnitType;
  user_id: number;
  variant_product: string;
  variation?: Record<string, any>[];
  video_provider: string;
  video_url?: string;
};
