const menus = [
  {
    url: "dashboard",
    name: "Dashboard",
    slug: "dashboard",
    icon: "desktop",
    gate: undefined,
  },
  {
    navheader: "Order Management",
  },
  {
    url: "#",
    name: "Orders",
    slug: "customers",
    icon: "users",
    gate: "passengers.index",
    submenu: [
      {
        url: "/orders",
        name: "All",
        slug: "clients",
        icon: "bx bx-right-arrow-alt",
        gate: "passengers.index",
      },
      {
        url: "/orders/pending",
        name: "Pending",
        slug: "register-clients",
        icon: "bx bx-right-arrow-alt",
        gate: "passengers.save",
      },
      {
        url: "/orders/confirmed",
        name: "Confirmed",
        slug: "clients",
        icon: "bx bx-right-arrow-alt",
        gate: "passengers.index",
      },
      {
        url: "orders/processing",
        name: "Processing",
        slug: "register-clients",
        icon: "bx bx-right-arrow-alt",
        gate: "passengers.save",
      },
      {
        url: "orders/out-for-delivery",
        name: "Out for delivery",
        slug: "clients",
        icon: "bx bx-right-arrow-alt",
        gate: "passengers.index",
      },
      {
        url: "orders/delivered",
        name: "Delivered",
        slug: "register-clients",
        icon: "bx bx-right-arrow-alt",
        gate: "passengers.save",
      },
      {
        url: "orders/returned",
        name: "Returned",
        slug: "clients",
        icon: "bx bx-right-arrow-alt",
        gate: "passengers.index",
      },
      {
        url: "orders/failed",
        name: "Failed",
        slug: "register-clients",
        icon: "bx bx-right-arrow-alt",
        gate: "passengers.save",
      },
      {
        url: "orders/canceled",
        name: "Canceled",
        slug: "register-clients",
        icon: "bx bx-right-arrow-alt",
        gate: "passengers.save",
      },
    ],
  },
  {
    navheader: "PRODUCT MANAGEMENT",
  },
  {
    url: "#",
    name: "Brands",
    slug: "app-email",
    icon: "envelope-pull",
    gate: "providers.index",
    submenu: [
      {
        url: "/brands/add",
        name: "Add new",
        slug: "providers",
        icon: "bx bx-right-arrow-alt",
        gate: "providers.save",
      },
      {
        url: "/brands",
        name: "list",
        slug: "register",
        icon: "envelope-pull",
        gate: "providers.index",
      },
    ],
  },
  {
    url: "#",
    name: "Categories",
    slug: "app-email",
    icon: "grid",
    gate: "managers.index",
    submenu: [
      {
        url: "/categories",
        name: "Categories",
        slug: "managers",
        gate: "managers.index",
      },
      {
        url: "/sub-categories",
        name: "Sub category",
        slug: "add-managers",
        gate: "managers.save",
      },
      {
        url: "/sub-sub-category",
        name: "Sub sub category",
        slug: "add-managers",
        gate: "managers.save",
      },
    ],
  },
  {
    url: "/attributes",
    name: "Attributes",
    slug: "add-managers",
    gate: "managers.save",
  },
  {
    url: "#",
    name: "InHouse Products",
    slug: "app-email",
    icon: "grid",
    gate: "sub_admins.index",
    submenu: [
      {
        url: "/products/in-house",
        name: "Products",
        slug: "sub-admins",
        gate: "sub_admins.index",
      },
      {
        url: "/bulk-import",
        name: "Bulk import",
        slug: "add-sub-admins",
        gate: "sub_admins.save",
      },
      {
        url: "/bulk-export",
        name: "Bulk Export",
        slug: "add-sub-admins",
        gate: "sub_admins.save",
      },
    ],
  },
  {
    url: "#",
    name: "Seller Products",
    slug: "app-email",
    icon: "grid",
    gate: "sub_admins.index",
    submenu: [
      {
        url: "/products/seller/new",
        name: "New Products",
        slug: "sub-admins",
        gate: "sub_admins.index",
      },
      {
        url: "/products/seller/approved",
        name: "Approved Products",
        slug: "add-sub-admins",
        gate: "sub_admins.save",
      },
      {
        url: "/products/seller/denied",
        name: "Denied Products",
        slug: "add-sub-admins",
        gate: "sub_admins.save",
      },
    ],
  },
  ///////// MARKETING SECTION ////////////////
  {
    navheader: "MARKETING SECTION",
    gate: "bookings.dashboard",
  },
  {
    url: "/stock",
    name: "Product Stock",
    slug: "bookings",
    icon: "notebook",
    gate: "bookings.dashboard",
  },
  {
    url: "/reviews",
    name: "Customer Reviews",
    slug: "trips",
    icon: "check-alt",
    gate: "requests.index",
  },
  {
    url: "/wish-list",
    name: "Product in wish list",
    slug: "bookings",
    icon: "notebook",
    gate: "bookings.dashboard",
  },
  {
    url: "/transactions",
    name: "Transactions",
    slug: "trips",
    icon: "check-alt",
    gate: "requests.index",
  },
  ///////// USER SECTION ////////////////
  {
    navheader: "USER SECTION",
    gate: "bookings.dashboard",
  },
  {
    url: "#",
    name: "Seller",
    slug: "app-reviews-types-menu",
    icon: "envelope-pull",
    gate: "reviews.users",
    submenu: [
      {
        url: "/sellers",
        name: "List",
        slug: "passenger-ratings",
        icon: "check-alt",
        gate: "reviews.users",
      },
      {
        url: "/seller/withdraws",
        name: "Withdraws",
        slug: "driver-ratings",
        icon: "check-alt",
        gate: "reviews.providers",
      },
    ],
  },
  {
    url: "/customers",
    name: "Customers",
    slug: "trips",
    icon: "check-alt",
    gate: "requests.index",
  },
  ///////// SUPPORT SECTION ////////////////
  {
    navheader: "SUPPORT SECTION",
    gate: "bookings.dashboard",
  },
  {
    url: "/messages",
    name: "Messages",
    slug: "messages",
    icon: "check-alt",
    gate: "requests.index",
  },
  {
    url: "/support-tickets",
    name: "Support ticket",
    slug: "trips",
    icon: "check-alt",
    gate: "requests.index",
  },
  ///////// BUSINESS SETTINGS ////////////////
  {
    navheader: "BUSINESS SETTINGS",
    gate: "bookings.dashboard",
  },
  {
    url: "/seller-settings",
    name: "Seller Settings",
    slug: "messages",
    icon: "check-alt",
    gate: "requests.index",
  },
  {
    url: "/payment-methods",
    name: "Payment method",
    slug: "messages",
    icon: "check-alt",
    gate: "requests.index",
  },
  {
    url: "/sms-module",
    name: "SMS module",
    slug: "messages",
    icon: "check-alt",
    gate: "requests.index",
  },

  {
    url: "#",
    name: "Shipping method",
    slug: "app-service-types-menu",
    icon: "envelope-pull",
    gate: "service_types.index",
    submenu: [
      {
        url: "/shipping-methods",
        name: "list",
        slug: "vehicle-types",
        icon: "envelope-pull",
        gate: "service_types.index",
      },
      {
        url: "/shipping-methods/settings",
        name: "Settings",
        slug: "add-vehicle-types",
        icon: "envelope-pull",
        gate: "service_types.save",
      },
    ],
  },
  {
    url: "/languages",
    name: "Languages",
    slug: "messages",
    icon: "check-alt",
    gate: "requests.index",
  },
  {
    url: "/social-login",
    name: "Social Login",
    slug: "messages",
    icon: "check-alt",
    gate: "requests.index",
  },
  {
    url: "/currecies",
    name: "Currencies",
    slug: "messages",
    icon: "check-alt",
    gate: "requests.index",
  },
  ///////// End BUSINESS SETTINGS ////////

  {
    navheader: "WEB & APP SETTINGS",
    gate: "revenues.dashboard",
  },
  {
    url: "/web-config",
    name: "Web config",
    slug: "transactions",
    icon: "check-alt",
    gate: "payments.index",
  },
  {
    url: "/mail-config",
    name: "Mail config",
    slug: "transactions",
    icon: "check-alt",
    gate: "payments.index",
  },
  {
    url: "/notifications",
    name: "Notifications",
    slug: "revenues",
    icon: "pulse",
    gate: "revenues.dashboard",
  },
  {
    url: "#",
    name: "Page setup",
    slug: "app-promocodes-menu",
    icon: "check-alt",
    gate: "promo_codes.index",
    submenu: [
      {
        url: "/terms-and-conditions",
        name: "Terms and conditions",
        slug: "promo-codes",
        icon: "check-alt",
        gate: "promo_codes.index",
      },
      {
        url: "/privacy-policy",
        name: "Privacy policy",
        slug: "add-promo-code",
        icon: "comments",
        gate: "promo_codes.save",
      },
      {
        url: "/about-us",
        name: "About us",
        slug: "promo-codes",
        icon: "check-alt",
        gate: "promo_codes.index",
      },
      {
        url: "/faq",
        name: "Faq",
        slug: "add-promo-code",
        icon: "comments",
        gate: "promo_codes.save",
      },
    ],
  },
  {
    url: "/social-media",
    name: "Social media",
    slug: "transactions",
    icon: "check-alt",
    gate: "payments.index",
  },

  ///////// REPORT& ANALYTICS ////////////////
  {
    navheader: "REPORT& ANALYTICS",
    gate: "wallets.dashboard",
  },
  {
    url: "/earnings-report",
    name: "Earning Report",
    slug: "passenger-wallets",
    icon: "envelope-pull",
    gate: "wallets.user.index",
  },
  {
    url: "/order-report",
    name: "Order Report",
    slug: "driver-wallets",
    icon: "comments",
    gate: "wallets.provider.index",
  },
  {
    url: "#",
    name: "Sale report",
    slug: "app-promocodes-menu",
    icon: "check-alt",
    gate: "promo_codes.index",
    submenu: [
      {
        url: "/sales/inhouse",
        name: "Inhouse Sale",
        slug: "promo-codes",
        icon: "check-alt",
        gate: "promo_codes.index",
      },
      {
        url: "/sales/seller",
        name: "Seller Sale",
        slug: "add-promo-code",
        icon: "comments",
        gate: "promo_codes.save",
      },
    ],
  },
  ///////// EMPLOYEE SECTION ////////////////
  {
    navheader: "EMPLOYEE SECTION",
    gate: "wallets.dashboard",
  },
  {
    url: "/employees/role",
    name: "Employee role",
    slug: "passenger-wallets-payment",
    icon: "check-alt",
    gate: "wallets.user.payments",
  },
  {
    url: "#",
    name: "Employees",
    slug: "app-promocodes-menu",
    icon: "check-alt",
    gate: "promo_codes.index",
    submenu: [
      {
        url: "/employees/add",
        name: "Add new",
        slug: "promo-codes",
        icon: "check-alt",
        gate: "promo_codes.index",
      },
      {
        url: "/employees/list",
        name: "List",
        slug: "add-promo-code",
        icon: "comments",
        gate: "promo_codes.save",
      },
    ],
  },
];

export default menus;
